### ISSUE TITLE
Create: Factories not working correctly

### ISSUE THREAD

**Issue by Evalir** [aragon/govern#239]
It seems that the transparent proxies implemented for the factories (#88) have introduced a very cryptic bug somewhere; I haven't found the case, but I do know that if we entirely remove the proxies and just use "vanilla" factories, contracts work as expected. [Here](https://rinkeby.etherscan.io/tx/0x654e8c526120b6619673729151ec4286ee837de91c4a244bdbf96617921a7376)'s an example of a TX to a GovernFactory to create a new DAO.

**Comment by nivida** [comment]
Could you add all the steps you already have done.. a small debugging report would help to speed up the process on our side :-)

**Comment by izqui** [comment]
I will take a look early next week

**Comment by izqui** [comment]
<img width="700" alt="image" src="https://user-images.githubusercontent.com/447328/101324387-78d75980-386a-11eb-9f32-743dfe4043ec.png">

it works on my machine™️: [see tx](https://rinkeby.etherscan.io/tx/0x0bd215671b707313be95769e9892a7d070474141d8b6e60c3b675d655101d0d7) 

I'm pretty sure this failed because of something else. Did you reuse the name?

**Comment by novaknole** [comment]
@Evalir 

I think I reproduced it, but only for your `to` contract address.  

Even if I pass `false` for `useProxies` variable, It still fails with the same error.  


Can you quickly point me when It shows an error and when it doesn't ?
